---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: default
  name: viva
  labels:
    app: viva
spec:
  replicas: 1
  selector:
    matchLabels:
      application: viva
  template:
    metadata:
      labels:
        application: viva
    spec:
      containers:
        - image: fazenda/ps
          imagePullPolicy: Always
          name: viva
          ports:
            - containerPort: 80
              protocol: TCP
          securityContext:
            privileged: false
      imagePullSecrets:
        - name: regcred
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: viva
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
  selector:
    application: viva
  type: ClusterIP

---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: viva-tls
  namespace: default
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`viva.fazenda.solutions`)
      services:
        - name: viva
          port: 80
  tls:
    certResolver: default
